### ISSUE TITLE
Bucket list of changes for v1.0.0

### ISSUE THREAD

**Issue by indexzero** [foreversd/forever#624]
### Breaking changes
- [ ] #373 All files need to be relative to the same root(s) by default. Or at least a sane set of cascading roots
- [ ] Make forever drop the `sudo` bit after starting processes
- [ ] Make forever save all "bookkeeping files" to a directory not relative to the current user
- [ ] #573 Options to run as a specific user
- [ ] Options to run from a JSON file (similar to, but not exactly the same as a procfile or dockerfile)
- [ ] Make --uid be the ACTUAL user instead of the `forever` uid. Rename that `fid`
- [ ] Have an up-to-date CHANGELOG again.
- [ ] Move from `process.nextTick` to `setImmediate`.
- [ ] Remove `--id` and `--uid` and replace them _both_ with `--name`
### Non breaking internal changes
- [ ] Replace `flatiron.cli` with [`nash`](https://github.com/scottcorgan/nash)
- [ ] Replace `vows` with `mocha`. Get to at least 80% test coverage.
- [ ] Setup [Appveyor](www.appveyor.com) for Windows users.
### Open Questions
- [ ] #529 should `killTree` be default?
### **MUCH** better documentation
- [ ] Document columns https://github.com/foreverjs/forever/issues/542
- [ ] #529 Document `--killTree`

**Resources**
https://gist.github.com/dillonkrug/25ee1397510aa4dec1d7
